version: '3.3'

services:
  db: #container de MySQL
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql/
    restart: always
    env_file:
      - db.env
    networks:
      - backend
  wordpress:
  
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - wp.env
    networks:
      - backend
volumes:
  db-data:

networks:
  backend:
    driver: bridge